spring:
  application:
    name: Products-Api
  datasource:
    url: jdbc:mysql:///e-commerceproject 
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true